/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Crypt {
  static base64ToBytes(base64Str: string): Array<number>
  static bytesToBase64(bytes: Uint8Array): string
  static hexToBytes(hex: string): Array<number>
}
